# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "just.plain.cool"
license = "MIT"
licenselink = "https://github.com/tcwill/just.plain.cool_hugo_theme/blob/master/LICENSE.md"
description = "A blog-forward theme that supports narrow screens"
homepage = "http://just.plain.cool/hugo-theme/"
tags = ["blog", "topics", "tags", "mobile"]
features = ["blog", "responsive"]
min_version = 0.17

[author]
  name = "Todd Williams"
  homepage = "http://just.plain.cool"

